### ISSUE TITLE
Deployment Issue on vercel

### ISSUE THREAD

**Issue by codistiano** [codistiano/QuesTrack#18]
I am not getting what is happening exactly, it just shows a 404 errors. Anybody with knowledge with vercel deployment can contribute here!!

**Comment by mikek1337** [comment]
did it start before or after the merge

**Comment by codistiano** [comment]
It wasn't even working when it was deployed at first

**Comment by mikek1337** [comment]
can you add me to your project on vercel if you can

**Comment by codistiano** [comment]
I have come to find out that it is not possible to deploy an project using EmbeddedJS.

You can read through this [discussion](https://github.com/vercel/vercel/discussions/4541).
